### ISSUE TITLE
UserWarning: Your connection pool seems unresponsive

### ISSUE THREAD

**Issue by 4uku** [jawah/niquests#105]
I get an _UserWarning_ if the number of requests more than the pool size. Is that normal? Should I change the pool size every time?
## Expected Result

```shell
Function main() {} Took 1.3624 seconds
```

## Actual Result

```shell
.venv/lib/python3.11/site-packages/urllib3/_async/connectionpool.py:1395: UserWarning: Your connection pool seems unresponsive, please try to increase the maxsize capacity or release connections manually. In case of pending requests, please consume them.
  await self.pool.wait_for_available_or_available_slot()
Function main() {} Took 3.1617 seconds
```

## Reproduction Steps

```python
import asyncio

from niquests import AsyncSession


def async_timeit(func):
    @wraps(func)
    async def timeit_wrapper(*args, **kwargs):
        start_time = time.perf_counter()
        result = await func(*args, **kwargs)
        end_time = time.perf_counter()
        total_time = end_time - start_time
        print(f'Function {func.__name__}{args} {kwargs} Took {total_time:.4f} seconds')
        return result
    return timeit_wrapper


@async_timeit
async def main() -> None:
    session = AsyncSession()
    tasks = [session.post(url="https://pie.dev/delay/1") for _ in range(11)]
    await asyncio.gather(*tasks)
    await session.close()


if __name__ == "__main__":
    asyncio.run(main())

```

## System Information

    $ python -m niquests.help

```json
{
  "charset_normalizer": {
    "version": "3.3.2"
  },
  "cryptography": {
    "version": "42.0.5"
  },
  "http1": {
    "h11": "0.14.0"
  },
  "http2": {
    "h2": "4.1.0"
  },
  "http3": {
    "enabled": true,
    "qh3": "0.15.1"
  },
  "idna": {
    "version": "3.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.11.8"
  },
  "niquests": {
    "version": "3.5.5"
  },
  "ocsp": {
    "enabled": true
  },
  "platform": {
    "release": "6.5.0-26-generic",
    "system": "Linux"
  },
  "system_ssl": {
    "version": "300000a0"
  },
  "urllib3.future": {
    "cohabitation_version": null,
    "version": "2.7.901"
  },
  "wassima": {
    "certifi_fallback": false,
    "enabled": true,
    "version": "1.1.0"
  }
}

```

**Comment by Ousret** [comment]
Let's analyze what your code shows us.

The `for _ in range(11)` explicitly tell us that you need 11 connections into your pool of connections to pursue this.
Niquests does not create disposable connection in async, and rather let you size it appropriately.

In your case, yes spawning 11 tasks concurrently will require 11 connection (the default is 10), so you'll have to do `AsyncSession(pool_maxsize=11)`. Or a high number you wish not to exceed like 256.

But there is another way. Leveraging multiplexing.

```python
import asyncio
import time
from functools import wraps

from niquests import AsyncSession


def async_timeit(func):
    @wraps(func)
    async def timeit_wrapper(*args, **kwargs):
        start_time = time.perf_counter()
        result = await func(*args, **kwargs)
        end_time = time.perf_counter()
        total_time = end_time - start_time
        print(f'Function {func.__name__}{args} {kwargs} Took {total_time:.4f} seconds')
        return result
    return timeit_wrapper


@async_timeit
async def main() -> None:
    session = AsyncSession(multiplexed=True)
    tasks = [session.post(url="https://pie.dev/delay/1") for _ in range(33)]
    responses = await asyncio.gather(*tasks)
    await session.gather()  # make sure to load lazy responses
    print(responses)
    await session.close()


if __name__ == "__main__":
    asyncio.run(main())
```

If this does answer appropriately your concern, feel free to close this.
Regards,

**Comment by 4uku** [comment]
Ok, it`s clear.

I run your code with `multiplexed=True` many times with Makefile and sometimes i still getting
`UserWarning: Your connection pool seems unresponsive, please try to increase the maxsize capacity or release connections manually. In case of pending requests, please consume them.
  await self.pool.wait_for_available_or_available_slot()`
  
```Makefile

  niquests_async_mplex:
	@for i in $$(seq 1 50); do \
		poetry run python src/p_niquests_async_mplex.py; \
	done
```
##My code
```python
  import asyncio

from niquests import AsyncSession

from utils import async_timeit


@async_timeit
async def main() -> None:
    session = AsyncSession(multiplexed=True)
    tasks = [session.post(url="https://pie.dev/delay/1") for _ in range(500)]
    responses = await asyncio.gather(*tasks)
    await session.gather()
    await session.close()


if __name__ == "__main__":
    asyncio.run(main())
```
## Actual result
```shell
Function main() {} Took 2.6493 seconds
Function main() {} Took 2.7243 seconds
Function main() {} Took 2.7258 seconds
Function main() {} Took 2.6848 seconds
Function main() {} Took 4.4647 seconds
Function main() {} Took 3.5406 seconds
Function main() {} Took 2.7642 seconds
Function main() {} Took 2.7090 seconds
Function main() {} Took 2.8285 seconds
/.venv/lib/python3.11/site-packages/urllib3/_async/connectionpool.py:1395: UserWarning: Your connection pool seems unresponsive, please try to increase the maxsize capacity or release connections manually. In case of pending requests, please consume them.
  await self.pool.wait_for_available_or_available_slot()
Function main() {} Took 10.1193 seconds
Function main() {} Took 2.8393 seconds
Function main() {} Took 2.7912 seconds
Function main() {} Took 2.6837 seconds
Function main() {} Took 2.6689 seconds
Function main() {} Took 2.6685 seconds
Function main() {} Took 2.7094 seconds
Function main() {} Took 2.6547 seconds
```

My apologies if I don't understand the obvious.

**Comment by Ousret** [comment]
Maybe I did not get your primary goal accordingly. Do you **want** the pool to allow infinite scaling automatically?
Because when I wrote this `for _ in range(33)` you sent back `for _ in range(500)`.
multiplexing saves the connection pool but not in a desire of "infinite scaling" as the server limit the number of concurrent streams per conn.

**Comment by 4uku** [comment]
I want to make several thousand requests and am looking for a better way to do it.

**Comment by trankov** [comment]
> I want to make several thousand requests and am looking for a better way to do it.

When I had the same need, I used `semaphore` from `asyncio` to limit the number of simultaneous requests, but run them in a single set of tasks. And it worked good.

**Comment by Ousret** [comment]
OK! So now that I have a better understanding of your goals,

I removed the "warning" and to make this effective, run `pip install urllib3.future -U`. The warning was kind of superfluous, was just there to say "you expected the whole thing to take a sec, but we can't.. because we don't have enough connection for it".

The code you've shown is OK, and the multiplexing example would be the best one to speed up things. You can size the pool of connections as you sees fit and try to find the sweet spot by yourself. Clearly, "10" isn't going to cut it if you are aiming for a large scale. See https://niquests.readthedocs.io/en/latest/user/quickstart.html#scale-your-session-pool for more information on the subject.

I consider this matter resolved, if not, ping me.
Regards,
