### ISSUE TITLE
Request/response mocking for testing purposes

### ISSUE THREAD

**Issue by amotl** [jawah/niquests#109]
Dear @Ousret,

we just tried to use the [responses] package together with niquests, and obviously it does not work out of the box. Maybe there is an easy solution?

With kind regards,
Andreas.

[responses]: https://pypi.org/project/responses/

**Comment by amotl** [comment]
Ah, right. I am now using initialization code like this. It perfectly works around the problem.

```python
def patch_niquests():
    from sys import modules

    import niquests
    import urllib3

    # Amalgamate the module namespace to make all modules aiming
    # to use `requests`, in fact use `niquests` instead.
    modules["requests"] = niquests
    modules["requests.adapters"] = niquests.adapters
    modules["requests.sessions"] = niquests.sessions
    modules["requests.exceptions"] = niquests.exceptions
    modules["requests.packages.urllib3"] = urllib3
```

https://github.com/panodata/grafana-wtf/pull/130#pullrequestreview-1969384629

**Comment by Ousret** [comment]
Hello,

Maybe you've missed it, but we did write about this https://niquests.readthedocs.io/en/latest/dev/migrate.html#maintainer-migration

regards,

**Comment by amotl** [comment]
Right, thank you very much.

Apparently, I haven't been able to find it back, because the page lacks corresponding keywords, and `response` has a typo, should be called `responses`.

When improving the documentation, please add keywords like "monkeypatch" to this documentation section.

I also think this detail is in the _wrong_ section, because it is not about **migration**, but about **integration** instead. In this case, it is about the integration with the `responses` package. Didn't you have another page which is exclusively about integration with other frameworks, like we improved with the requests-cache module last time? [^1] Personally, I would expect all those items to be present on a single page.

[^1]: Apologies, I can't find it back, using `integration` as a keyword yields not search results.

**Comment by amotl** [comment]
As you can see, we are really strong proponents for adding this [monkeypatching code snippet](https://github.com/jawah/niquests/issues/109#issuecomment-2067832646) to the niquests package itself, so it becomes more re-usable for 3rd party applications, which use the `niquests` package directly, but also transitively.

If you are not comfortable adding this snippet the main module namespace, maybe you could consider adding it to `niquests.testing`, like how others are doing it, in order to support their downstream libraries and applications by providing corresponding testing helpers to them?

On the other hand, you already mentioned on another occasion that you are not comfortable adding this snippet to the code base. So, if we haven't been able to convince you up until now, we will surely stop bothering you about it ;].

**Comment by Ousret** [comment]
> maybe you could consider adding it to niquests.testing, like how others are doing it, in order to support their downstream libraries and applications by providing corresponding testing helpers to them?

I'll think about it. And propose a implementation that would suit all of us. Will keep you posted.

regards,

**Comment by Ousret** [comment]
update: "responses" agreed to review a PR for Niquests optional support. I will propose a PR at my early.

**Comment by Ousret** [comment]
update: unfortunately we did not get attention on our attempt to bring "responses" compatible with both Niquests and Requests.

It's probable that "responses" won't dedicate time to review any PR on that specific topic unless someone else "than me" would start the process.

In the meantime, two possibilities are offered to anyone stumbling in that issue:

- A) Install my patch directly via git `https://github.com/Ousret/responses/tree/support-niquests` 
- B) Patch sys.module as presented in the docs https://niquests.readthedocs.io/en/latest/dev/migrate.html#maintainer-migration

As it is not an issue with Niquests, I am closing it.

Regards,
