### ISSUE TITLE
caching requests

### ISSUE THREAD

**Issue by ArtemIsmagilov** [jawah/niquests#115]
Having read your source code, I see that you cache any client requests to the server. perhaps this really increases the speed of information transfer. won't this interfere with the display of real data from the server? After all, the result is not from the server, but from the cache? It seems that I do not understand the ideal architecture of http clients at a professional level. Why such a multiple increase in productivity? It seems like an IO bound operation and we’re just waiting and parsing the metadata...

**Comment by Ousret** [comment]
You are mistaken. We do not cache the response neither we cache the request.
It is not Niquests job to cache a server response. You probably misinterpreted some minor optimization for caching either the request or response. try to assemble a piece of code that shows exactly that, you will see that it is not.

regards,

**Comment by ArtemIsmagilov** [comment]
@Ousret, I apologize, apparently I didn’t understand the following part of the code correctly https://github.com/jawah/niquests/blob/66f5ceab5b0ed36fe350f4ee8f81e377351249df/src/niquests/_async.py#L227
thank you very much for the clarification on this issue

**Comment by Ousret** [comment]
No worries. It happen.
