### ISSUE TITLE
Make it possible to track raw download size

### ISSUE THREAD

**Issue by jkbrzt** [jawah/niquests#127]
When `Content-Encoding` is applied, we only get access to the decoded data. 

HTTPie’s `--download` feature would benefit from having continuous access to a raw downloaded bytes counter so that it can provide a meaningful progress bar and validate that the downloaded size matches `Content-Length` (https://github.com/httpie/cli/issues/423, https://github.com/httpie/cli/pull/1531).

**Comment by Ousret** [comment]
As I promised. It is now possible to track the real download speed. see version 3.7 changes
The decompression speed can be inferred also (based on output size).
