### ISSUE TITLE
Bug: __repr__ method implementation error in CaseInsensitiveDict class

### ISSUE THREAD

**Issue by BenRmy** [jawah/niquests#129]
An error will be reported when printing the headers attribute of the response.

Traceback (most recent call last):
  File "C:\work\App\test.py", line 5, in <module>
    print(resp.headers)
  File "C:\work\App\.env\lib\site-packages\niquests\structures.py", line 146, in __repr__
    return str(dict(self.items()))
ValueError: dictionary update sequence element #7 has length 3; 2 is required

Deleting the items method it calls can print headers normally.

## Version Information
{
  "charset_normalizer": {
    "version": "3.3.2"
  },
  "http1": {
    "h11": "0.14.0"
  },
  "http2": {
    "jh2": "5.0.3"
  },
  "http3": {
    "enabled": true,
    "qh3": "1.0.8"
  },
  "idna": {
    "version": "3.4"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.10.11"
  },
  "niquests": {
    "version": "3.6.6"
  },
  "ocsp": {
    "enabled": true
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "system_ssl": {
    "version": "1010114f"
  },
  "urllib3.future": {
    "cohabitation_version": null,
    "version": "2.7.914"
  },
  "wassima": {
    "certifi_fallback": false,
    "enabled": true,
    "version": "1.1.1"
  }
}

**Comment by Ousret** [comment]
Indeed, this was a minor bug following a performance optimization.
It is fixed in latest, run `pip install niquests -U`.

regards,
