### ISSUE TITLE
feature request: use this package without change old code

### ISSUE THREAD

**Issue by trim21** [jawah/niquests#139]
We want to try niquests in our code, but it will install `urllib3.future` and it will override some files from official urllib3 package. Which may cause some unexpected effect on our existing code.

Is there a way to use this package with requests, without interfering urllib3?

**Comment by Ousret** [comment]
Unfortunately, at the time being, we cannot do this by default. For reasons explained in https://github.com/jawah/urllib3.future?tab=readme-ov-file#notes--frequently-asked-questions and https://niquests.readthedocs.io/en/latest/community/faq.html#what-is-urllib3-future and https://github.com/jawah/urllib3.future/issues/91

**Your options are as follow:**

- https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-no-binary
  - `URLLIB3_NO_OVERRIDE=true pip install niquests --no-binary urllib3-future`  at the price to lose the high compat between Requests and Niquests (extensions, etc...)
- Or section `How can I restore urllib3 to the "legacy" version?` in urllib3-future README

Finally, I would argue that:

- urllib3-future has a better compatibility range than its predecessor (Python 3.7 and OpenSSL <1.1.1 supported)
- urllib3-future is thoroughly tested against software than deeply interact with urllib3 internals https://github.com/jawah/urllib3.future/actions/runs/10463745326
- urllib3-future solve issues in often less than 48 hours
- urllib3 did break things several times [like there](https://github.com/boto/botocore/issues/2926#issuecomment-1538900780), and it's not going to stop anytime soon with what is coming.

regards,
