### ISSUE TITLE
Support for requests-cache

### ISSUE THREAD

**Issue by glensc** [jawah/niquests#156]
I thought to [give niquests][1] a try, but I realized I'm using requests cache.

[1]: https://github.com/Taxel/PlexTraktSync/pull/2081

How would you use niquests and projects that extends requests?

I fired the same question to requests-cache repo as well:
- https://github.com/requests-cache/requests-cache/issues/1022

**Comment by glensc** [comment]
perhaps should just override `sys.modules`? 

- https://niquests.readthedocs.io/en/latest/dev/migrate.html#maintainer-migration

**Comment by Ousret** [comment]
You have two options.

First, following https://niquests.readthedocs.io/en/latest/community/recommended.html#requests-cache
Inherit CacheMixin with our Session.
The solution isn't perfect, but it work flawlessly.

Second, you may override Requests using sys.module (via https://niquests.readthedocs.io/en/latest/dev/migrate.html#maintainer-migration) only if you are not a library but an executable standalone.
To avoid forcing other non tested library to switch.

Almost every requests extension are compatible using methods described in our docs.

Regards,

**Comment by glensc** [comment]
The import trick doesn't work:

```
  File "lib/python3.9/site-packages/trakt/core.py", line 17, in <module>
    from requests_oauthlib import OAuth2Session
  File "python-3.9/lib/python3.9/site-packages/requests_oauthlib/__init__.py", line 13, in <module>
    if requests.__version__ < "2.0.0":
TypeError: '<' not supported between instances of 'module' and 'str'
```

That package had other non-compatible imports as well:
- https://github.com/requests/requests-oauthlib/blob/c003c22eceb9e54a7cfe242b7976412a2c98a972/requests_oauthlib/oauth1_auth.py#L7
