### ISSUE TITLE
verify=False is not inherited when creating a session

### ISSUE THREAD

**Issue by Anthonybelui** [jawah/niquests#165]
## Problem Description
When creating a session with verify=False parameter, subsequent requests through this session do not inherit this setting. This contradicts the expected behavior, as all session parameters should be inherited.

## Steps to Reproduce
```python
import niquests

# Create session with verify=False
session = niquests.Session()
session.verify = False

# Make request through the session
response = session.get('https://example.com')  # verify=False is not applied
# niquests.exceptions.SSLError: HTTPSConnectionPool(host=.......
```

## Expected Behavior
When setting verify=False for a session, all subsequent requests through this session should be executed with SSL verification disabled.

## Current Behavior
Requests through the session ignore the set verify=False value and continue to perform SSL verification.

## Additional Context
This can be critical for test environments or systems using self-signed certificates.

## System Information
```json
{
  "charset_normalizer": {
    "version": "3.4.0"
  },
  "http1": {
    "h11": "0.14.0"
  },
  "http2": {
    "jh2": "5.0.3"
  },
  "http3": {
    "enabled": true,
    "qh3": "1.2.1"
  },
  "idna": {
    "version": "3.10"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.12.6"
  },
  "niquests": {
    "version": "3.10.1"
  },
  "ocsp": {
    "enabled": true
  },
  "platform": {
    "release": "11",
    "system": "Windows"
  },
  "system_ssl": {
    "version": "300000f0"
  },
  "urllib3.future": {
    "cohabitation_version": null,
    "version": "2.11.903"
  },
  "wassima": {
    "certifi_fallback": false,
    "enabled": true,
    "version": "1.1.4"
  }
}
```

**Comment by Ousret** [comment]
Fixed in https://github.com/jawah/niquests/pull/167
Will be published in next patch version.
