### ISSUE TITLE
Problem with uvicorn and uvloop and urllib3 when call to shutdown

### ISSUE THREAD

**Issue by calope** [jawah/niquests#166]
Error with asyncio and uvloop, and urllib3. Call to shutdown

/lib/python3.9/site-packages/urllib3/contrib/ssa/__init__.py", line 81, in close
    self._sock.shutdown(SHUT_RD)
  File "uvloop/pseudosock.pyx", line 155, in uvloop.loop.PseudoSocket.shutdown
  File "uvloop/pseudosock.pyx", line 19, in uvloop.loop.PseudoSocket._na
TypeError: transport sockets do not support shutdown() method

## Expected Result

Depends of implementation maybe no call to shutdown, only close?

## Actual Result

/lib/python3.9/site-packages/urllib3/contrib/ssa/__init__.py", line 81, in close
    self._sock.shutdown(SHUT_RD)
  File "uvloop/pseudosock.pyx", line 155, in uvloop.loop.PseudoSocket.shutdown
  File "uvloop/pseudosock.pyx", line 19, in uvloop.loop.PseudoSocket._na
TypeError: transport sockets do not support shutdown() method

## Reproduction Steps

I call with fastapi application with uvicorn and uvloop, and when I made a simple post, get the previous error.

## System Information

    $ python -m niquests.help

```json
{
  "charset_normalizer": {
    "version": "3.4.0"
  },
  "http1": {
    "h11": "0.14.0"
  },
  "http2": {
    "jh2": "5.0.3"
  },
  "http3": {
    "enabled": true,
    "qh3": "1.2.1"
  },
  "idna": {
    "version": "3.10"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.9.19"
  },
  "niquests": {
    "version": "3.10.1"
  },
  "ocsp": {
    "enabled": true
  },
  "platform": {
    "release": "24.1.0",
    "system": "Darwin"
  },
  "system_ssl": {
    "version": "30300010"
  },
  "urllib3.future": {
    "cohabitation_version": null,
    "version": "2.11.903"
  },
  "wassima": {
    "certifi_fallback": false,
    "enabled": true,
    "version": "1.1.4"
  }
}
```

**Comment by calope** [comment]
Additional info, I use python 3.9, and other libraries used:

➜ poetry show uvicorn
 name         : uvicorn                         
 version      : 0.32.0                          
 description  : The lightning-fast ASGI server. 

dependencies
 - click >=7.0
 - h11 >=0.8
 - typing-extensions >=4.0

pepapi on  feat/use_niquests [$!] is 📦 0.1.8 
➜ poetry show uvloop 
 name         : uvloop                                                    
 version      : 0.21.0                                                    
 description  : Fast implementation of asyncio event loop on top of libuv 

pepapi on  feat/use_niquests [$!] is 📦 0.1.8 
➜ poetry show fastapi
 name         : fastapi                                                                                
 version      : 0.115.3                                                                                
 description  : FastAPI framework, high performance, easy to learn, fast to code, ready for production 

dependencies
 - pydantic >=1.7.4,<1.8 || >1.8,<1.8.1 || >1.8.1,<2.0.0 || >2.0.0,<2.0.1 || >2.0.1,<2.1.0 || >2.1.0,<3.0.0
 - starlette >=0.40.0,<0.42.0
 - typing-extensions >=4.8.0

**Comment by Ousret** [comment]
It is fixed and will be made available in next patch version of urllib3-future.

**Comment by Ousret** [comment]
I suspect something seems wrong with your environment.

Run `cat lib/python3.9/site-packages/urllib3_future/contrib/ssa/init.py` and inspect the content
There's a chance it does not match https://github.com/jawah/urllib3.future/blob/main/src/urllib3/contrib/ssa/__init__.py

I could reproduce the bug, and then I verified that the version fixed this.

regards,

**Comment by calope** [comment]
Thanks a lot.... the correct trace was, but I don't know why close doesn't exist???

/site-packages/urllib3_future/contrib/ssa/__init__.py", line 85, in close
    self._sock.close()
  File "uvloop/pseudosock.pyx", line 149, in uvloop.loop.PseudoSocket.close
  File "uvloop/pseudosock.pyx", line 19, in uvloop.loop.PseudoSocket._na
TypeError: transport sockets do not support close() method

**Comment by calope** [comment]
I think is not close method... is write_eof() or detach... I don't know...

Similar problem...
https://github.com/MagicStack/uvloop/issues/241

**Comment by Ousret** [comment]
I see. I will try another complementary fix asap. Linux uvloop does not have this issue. Mac does it seems.
But in the meantime, remove wrap the close call as proposed in the linked issue.

**Comment by calope** [comment]
Thanks a lot

**Comment by Ousret** [comment]
It should be definitely fixed in https://github.com/jawah/urllib3.future/releases/tag/2.11.905

**Comment by calope** [comment]
Thank you very much for everything. It works perfectly on Mac.
