### ISSUE TITLE
Mypy complains about the type hint for quic_cache_layer.add_domain.

### ISSUE THREAD

**Issue by nakoo** [jawah/niquests#189]
## Expected Result
```bash
Success: no issues found in 1 source file
```

## Actual Result
```bash
test.py:15: error: Item "MutableMapping[tuple[str, int], tuple[str, int] | None]" of "MutableMapping[tuple[str, int], tuple[str, int] | None] | QuicSharedCache" has no attribute "add_domain"  [union-attr]
Found 1 error in 1 file (checked 1 source file)
```

## Reproduction Steps

```python
import asyncio
import time
import niquests
from urllib.parse import urlparse

async def request(url: str) -> niquests.Response | None:
    hostname = str(urlparse(url).hostname)
    response = None
    error_msg = None

    try:
        start = time.perf_counter()
        async with niquests.AsyncSession(happy_eyeballs=True) as session:
            async with asyncio.timeout(30):
                session.quic_cache_layer.add_domain(hostname)
                response = await session.get(url, timeout=5)
                response.raise_for_status()
    except niquests.RequestException as e:
        error_msg = f"Niquests Error: {e}"
    except TimeoutError:
        error_msg = f"Niquests were forcibly timed out"
    except Exception as e:
        error_msg = f"Unexpected Error: {e}"
    finally:
        end = time.perf_counter()
        if error_msg:
            print(f"{error_msg} | {round(end - start, 2)}")

    return response

async def test() -> None:
    url = "https://http3check.net/"
    response = await request(url)

    if not response:
        raise ValueError("No response")

    print(response.headers)

def main() -> None:
    asyncio.run(test())

if __name__ == "__main__":
    main()



```

## System Information

    $ python -m niquests.help

```json
{
  "charset_normalizer": {
    "version": "3.4.0"
  },
  "http1": {
    "h11": "0.14.0"
  },
  "http2": {
    "jh2": "5.0.4"
  },
  "http3": {
    "enabled": true,
    "qh3": "1.2.1"
  },
  "idna": {
    "version": "3.10"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.12.7"
  },
  "niquests": {
    "version": "3.11.3"
  },
  "ocsp": {
    "enabled": true
  },
  "platform": {
    "release": "6.6.64",
    "system": "Linux"
  },
  "system_ssl": {
    "name": "OpenSSL 3.3.2 3 Sep 2024",
    "version": "30300020"
  },
  "urllib3.future": {
    "cohabitation_version": null,
    "version": "2.12.903"
  },
  "wassima": {
    "certifi_fallback": false,
    "enabled": true,
    "version": "1.1.5"
  },
  "websocket": {
    "enabled": false,
    "wsproto": null
  }
}
```

**Comment by Ousret** [comment]
I understand how surprising this is.

Here, mypy is right, technically speaking, `session.quic_cache_layer` can be something else. Mypy does not infer (can't) that you did not touch the default. This can be useful when for instance you want to inject a simple `MutableMapping` that hide a redis connector behind it. Niquests support having a custom implementation of `MutableMapping` in `session.quic_cache_layer` instead of the default `QuicSharedCache` instance. 

Our initial recommendation is to check whether `session.quic_cache_layer` has `add_domain` method in it to make mypy happy with it. Insert something like `assert hasattr(session.quic_cache_layer, "add_domain")` just before the problematic / ambiguous call. We may revisit later allowed types in `quic_cache_layer` to improve the general UX.

Moreover, by my reading of your intent I can propose a simplified version of your script.
Look :point_down: 

```python
from __future__ import annotations

import asyncio
import niquests

async def request(url: str) -> niquests.Response | None:
    response = None
    error_msg = None

    start = asyncio.get_running_loop().time()

    try:
        async with niquests.AsyncSession(happy_eyeballs=True, disable_http1=True, disable_http2=True) as session:
            response = (
                await session.get(url, timeout=(5, 30))
            ).raise_for_status()
    except niquests.RequestException as e:
        error_msg = f"Niquests Error: {e}"
    except Exception as e:
        error_msg = f"Unexpected Error: {e}"
    finally:
        end = asyncio.get_running_loop().time()
        if error_msg:
            print(f"{error_msg} | {round(end - start, 2)}")

    return response

async def main() -> None:
    response = await request("https://http3check.net/")

    if not response:
        raise ValueError("No response")

    print(response)
    print(response.elapsed)
    print(response.headers)


if __name__ == "__main__":
    asyncio.run(main())
```

Hope this clarify.
Regards,

**Comment by nakoo** [comment]
Thank you for the suggestion. I'm curious whether explicitly stating to disable other protocols would be more effective in this case, as I have read documentation recommending the use of `quic_cache_layer.add_domain`. I'm a bit concerned that explicitly disabling other protocols could lead to RuntimeError.

https://niquests.readthedocs.io/en/v3.11.3/user/advanced.html#specify-http-3-capable-endpoint-preemptively
https://niquests.readthedocs.io/en/v3.11.3/user/advanced.html#http-2-with-prior-knowledge

**Comment by Ousret** [comment]
>  I'm curious whether explicitly stating to disable other protocols would be more effective in this case [...] I'm a bit concerned that explicitly disabling other protocols could lead to RuntimeError.

You are correct, indeed. This could be a side effect, and it is planed to review that behaviour as soon as we can.
The error is triggered wrongfully when http3 isn't reachable and tries to downgrade, but there's no available protocol for it.

Regards,
