### ISSUE TITLE
Latest release fails - ImportError: cannot import name 'ConnectionInfo' from 'urllib3'

### ISSUE THREAD

**Issue by lucaspar** [jawah/niquests#90]
## Expected Result

No import issues with latest urllib3 (v2.2.1)

## Actual Result

https://github.com/jawah/niquests/commit/40e1d6a6638ff20d695dd10408100275eae9cded#r139358101

```txt
ImportError: cannot import name 'ConnectionInfo' from 'urllib3' (/home/user/.cache/pypoetry/virtualenvs/project-py3.11/lib/python3.11/site-packages/urllib3/__init__.py)
```

## Reproduction Steps

```bash
poetry run python -c "import niquests"
```

## System Information

Python 3.11.8

```bash
poetry show | grep 'urllib|niquest'
niquests                  3.5.1           Niquests is a simple, yet elegant...
urllib3                   2.2.1           HTTP library with thread-safe con...
urllib3-future            2.6.902         urllib3.future is a powerful HTTP...
```

**Comment by lucaspar** [comment]
Potentially related:

+ https://github.com/jawah/urllib3.future/issues/91

**Comment by Ousret** [comment]
OK. This is now fixed, a patch has been made. I will answer your other question at the other issue.
