### ISSUE TITLE
Speed comparison results

### ISSUE THREAD

**Issue by air55555** [jawah/niquests#93]
There is text about  Speed comparison results
performance measured when leveraging a multiplexed connection with or without uses of any form of concurrency as of november 2023. The research compared httpx, requests, aiohttp against niquests. [↩](https://github.com/jawah/niquests?tab=readme-ov-file#user-content-fnref-10-59a7b4f7471ddc9ac23997a8e4057147)
## Expected Result
Link to Speed comparison results

## Actual Result
Link to feature comparison

## Reproduction Steps
go to https://github.com/jawah/niquests
find Niquests, is the “Safest, Fastest[1](https://github.com/jawah/niquests#user-content-fn-10-59a7b4f7471ddc9ac23997a8e4057147)
Click [1]

**Comment by Ousret** [comment]
OK. I am going to produce updated results and share them asap including code & method in gist.

**Comment by Ousret** [comment]
Just published them. You may find appropriate results, code & method used in the readme and external repo mentioned.

regards,

**Comment by air55555** [comment]
> Just published them. You may find appropriate results, code & method used in the readme and external repo mentioned.
> 
> regards,

Thank you for the fast reaction and perfect scoring realisation.
