### ISSUE TITLE
[FYI] `niquests` is now available from ArchLinux User Repository as `python-niquests-git`

### ISSUE THREAD

**Issue by kseistrup** [jawah/niquests#95]
[ This is an informational message only. No action is required on your part, and the issue can be closed at your discretion. ]

I thought you'd like to know that ArchLinux users can now install `niquests` directly from ArchLinux User Repository (AUR) as `python-niquests-git`:

+ https://aur.archlinux.org/packages/python-niquests-git

The package can be installed using an [AUR helper](https://wiki.archlinux.org/title/AUR_helpers), e.g. `yay`:

```sh
» yay -S python-niquests-git
```

This will build the python module from the latest commit, and install it along with the README and the LICENSE.

:pray:

**Comment by Ousret** [comment]
Dully noted. Thank you.
